In [51]:
import os
import cv2
import numpy as np
from ultralytics import YOLO

In [2]:
model = YOLO("yolov8x.pt")

In [3]:
img = cv2.imread("img.png")

In [4]:
prediction = model.predict(img)


0: 576x640 3 persons, 1 sports ball, 45.4ms
Speed: 0.5ms preprocess, 45.4ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)


In [5]:
print(prediction)

[{ '_keys': ('boxes', 'masks', 'probs'),
  'boxes': ultralytics.yolo.engine.results.Boxes
type:  torch.Tensor
shape: torch.Size([4, 6])
dtype: torch.float32
tensor([[ 44.69575,  83.30696, 161.10619, 264.29254,   0.93995,   0.00000],
        [280.21820, 210.83795, 367.84811, 312.59491,   0.93454,   0.00000],
        [ 78.80675, 251.39590, 106.85529, 279.60107,   0.91466,  32.00000],
        [147.24854,  83.29745, 204.95674, 278.91458,   0.88939,   0.00000]], device='cuda:0'),
  'masks': None,
  'names': { 0: 'person',
             1: 'bicycle',
             2: 'car',
             3: 'motorcycle',
             4: 'airplane',
             5: 'bus',
             6: 'train',
             7: 'truck',
             8: 'boat',
             9: 'traffic light',
             10: 'fire hydrant',
             11: 'stop sign',
             12: 'parking meter',
             13: 'bench',
             14: 'bird',
             15: 'cat',
             16: 'dog',
             17: 'horse',
             18: 

In [7]:
boxes = prediction[0]
for box in boxes:
	print(dir(box[0]))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_keys', 'boxes', 'cpu', 'cuda', 'keys', 'masks', 'names', 'numpy', 'orig_img', 'orig_shape', 'pandas', 'path', 'plot', 'probs', 'to', 'update']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_keys', 'boxes', 'cpu', 'cuda', 'keys', 'masks', 'names', 'numpy', 'orig_img', 'or

In [16]:
boxes = prediction[0]
print(boxes.boxes)
# for box in boxes:
# 	print(box.boxes)
# 	break

tensor([[ 44.69575,  83.30696, 161.10619, 264.29254,   0.93995,   0.00000],
        [280.21820, 210.83795, 367.84811, 312.59491,   0.93454,   0.00000],
        [ 78.80675, 251.39590, 106.85529, 279.60107,   0.91466,  32.00000],
        [147.24854,  83.29745, 204.95674, 278.91458,   0.88939,   0.00000]], device='cuda:0')


In [53]:
imgCopy = img.copy()
for box in boxes.boxes:
	_box = box.cpu().numpy().xywh[0]
	x = int(np.round(_box[0]))
	y = int(np.round(_box[1]))
	w = int(np.round(_box[2]))
	h = int(np.round(_box[3]))
	args = (imgCopy, (x, y), (x+w, y+h), (0, 255, 0), 2)
	print(args)
	cv2.rectangle(*args)
# Boxes are not
cv2.imwrite("img2.png", imgCopy)

(array([[[230, 240, 243],
        [230, 240, 243],
        [230, 240, 243],
        ...,
        [230, 240, 243],
        [230, 240, 243],
        [230, 240, 243]],

       [[230, 240, 243],
        [230, 240, 243],
        [230, 240, 243],
        ...,
        [230, 240, 243],
        [230, 240, 243],
        [230, 240, 243]],

       [[230, 240, 243],
        [233, 242, 246],
        [ 70, 136, 114],
        ...,
        [240, 248, 252],
        [230, 240, 243],
        [230, 240, 243]],

       ...,

       [[230, 240, 243],
        [230, 240, 243],
        [129, 167, 158],
        ...,
        [233, 242, 246],
        [230, 240, 243],
        [230, 240, 243]],

       [[230, 240, 243],
        [230, 240, 243],
        [233, 242, 246],
        ...,
        [230, 240, 243],
        [230, 240, 243],
        [230, 240, 243]],

       [[230, 240, 243],
        [230, 240, 243],
        [230, 240, 243],
        ...,
        [230, 240, 243],
        [230, 240, 243],
        [230, 240, 243]

True